database = 'trackify'
database_user = 'mahmooz'
database_password = 'mahmooz'
database_host = '0.0.0.0'
secret_key = 'my_super_secret_key'
client_id = "9084e51545cd454c8436bc9b7ddfd88c"
client_secret = "09624ad86bf44b32bcfa1bf5c9ccc7da"
scope = "user-library-read playlist-read-private user-read-playback-state user-read-currently-playing user-modify-playback-state"
redirect_uri = "http://localhost:5000/spotify/callback"
jwt_secret_key = "dev"
jwt_access_token_expires = 60 * 60 # 1 hour
jwt_refresh_token_expires = False
